name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initial build
      run: | 
        make build-initial
      env:
        APP_ENV: dev
        USER_UID: 1000
        USER_GID: 1000
        HOSTNAME: 127.0.0.1
        DATABASE_CONTAINER_NAME: pg-fleet
        DATABASE_NAME: fleet
        DATABASE_USER: fleet-user
        DATABASE_PASSWORD: fleet-user-password
        PHP_VERSION: 8.2
        APP_FOLDER: ./app
        APP_SECRET: fulll_hiring_secret
        DATABASE_URL: postgresql://fleet-user:fleet-user-password@127.0.0.1:5432/fleet
        MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
        APP_DEBUG: true

    - name: Database Initialize
      run: make database-init

    - name: Run cs-fixer
      run: make fix-cs

    - name: Run phpstan
      run: make php-stan

    - name: Run Test Behat
      run: make tests-behat
      
    - name: Run Test PhpUnit
      run: make tests-phpunit
